export default {
  font: {
    family:
      'MaisonNeue, NibPro, MaisonNeueExtended, MaisonNeueBook, MaisonNeueExtendedBook, MaisonNeueExtended, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
    fontFamily: {
      primary: 'MaisonNeue',
      secondary: 'NibPro',
      MaisonNeueExtendedBook: 'MaisonNeueExtendedBook',
      MaisonNeueBook: 'MaisonNeueBook',
      MaisonNeueExtended: 'MaisonNeueExtended',
      NibPro: 'MaisonNeueBook',
    },
    sizes: {
      xxsmall: '12px',
      xsmall: '14px',
      small: '16px',
      medium: '18px',
      large: '20px',
      xlarge: '22px',
      xxlarge: '25px',
      xxxlarge: '30px',
      larger: '33px',
      largest: '55px',
      huge: '60px',
    },
    height: {
      xxsmall: '12px',
      xsmall: '14px',
      small: '20px',
      medium: '22px',
      large: '24px',
      xlarge: '26px',
      xxlarge: '28px',
      xxxlarge: '34px',
      larger: '33px',
      largest: '55px',
      huge: '65px',
    },
  },
  colors: {
    primary: 'ffffff',
    secondary: 'cfcfcf',
    tertiary: '121212',
  },
  spacings: {
    xxsmall: '5px',
    xsmall: '10px',
    small: '15px',
    medium: '20px',
    large: '40px',
    xlarge: '60px',
    xxlarge: '70px',
  },
};
